// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJNGg2ZPrNm6d31t0ltyws5R9wszS2eY',
    appId: '1:67112430404:web:3eda3430f6aec8c1ca0511',
    messagingSenderId: '67112430404',
    projectId: 'peguemonte',
    authDomain: 'peguemonte.firebaseapp.com',
    storageBucket: 'peguemonte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAnDB4bqm8Cc6vACHxtYxuLn1DMEeQVEw',
    appId: '1:67112430404:android:92757f0cac653720ca0511',
    messagingSenderId: '67112430404',
    projectId: 'peguemonte',
    storageBucket: 'peguemonte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrMTLCu4HBwuyRFPAB6oRCcDWBKQiLoI',
    appId: '1:67112430404:ios:5df984509393a441ca0511',
    messagingSenderId: '67112430404',
    projectId: 'peguemonte',
    storageBucket: 'peguemonte.firebasestorage.app',
    iosBundleId: 'com.example.pegueEMonte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrMTLCu4HBwuyRFPAB6oRCcDWBKQiLoI',
    appId: '1:67112430404:ios:5df984509393a441ca0511',
    messagingSenderId: '67112430404',
    projectId: 'peguemonte',
    storageBucket: 'peguemonte.firebasestorage.app',
    iosBundleId: 'com.example.pegueEMonte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSJNGg2ZPrNm6d31t0ltyws5R9wszS2eY',
    appId: '1:67112430404:web:618bcb58fc59553eca0511',
    messagingSenderId: '67112430404',
    projectId: 'peguemonte',
    authDomain: 'peguemonte.firebaseapp.com',
    storageBucket: 'peguemonte.firebasestorage.app',
  );
}
